# Generated by Django 3.2.8 on 2022-02-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyapp', '0003_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
